Randomizer.SMZ3/Config.cs
Randomizer.SMZ3/Filler.cs
Randomizer.SMZ3/Item.cs
Randomizer.SMZ3/ListExtensions.cs
Randomizer.SMZ3/Location.cs
Randomizer.SMZ3/Patch.cs
Randomizer.SMZ3/Playthrough.cs
Randomizer.SMZ3/Randomizer.cs
Randomizer.SMZ3/Region.cs
Randomizer.SMZ3/Regions/SuperMetroid/Brinstar/Green.cs
Randomizer.SMZ3/Regions/SuperMetroid/Brinstar/Pink.cs
Randomizer.SMZ3/Regions/Zelda/GanonTower.cs
Randomizer.SMZ3/Regions/Zelda/HyruleCastle.cs
Randomizer.SMZ3/Regions/Zelda/LightWorld/NorthEast.cs
Randomizer.SMZ3/Regions/Zelda/LightWorld/NorthWest.cs
Randomizer.SMZ3/Regions/Zelda/LightWorld/South.cs
Randomizer.SMZ3/World.cs

This PR evolves the `Filler` to do location weighting for a single player seed, and handles difference under keysanity.
Additional behavioral changes:
- Reorder morphs before moonpearls. Better to possibly move moonpearls up from their last quarter than morphs up from their last half of the list.
- Non-dungeon item pools are shuffled as a common pools from all worlds.
- Locations are shuffled once before dungeon assumed fill, and once (plus weight) for the rest of the items.
- Weight values are simplified numbers taken from the v10.2 PHP implementation:
- Brinstar Green: -6
- Brinstar Pink: -4
- Light World, only affecting sphere 1 location:
- North West: -14
- North East, South, Hyrule Castle: -10
What constitutes a "sphere 1 location" in Hyrule Castle needs additional consideration. The …

Prepare Filler for single player weighting and keysanity

---

Randomizer.SMZ3/Filler.cs

The item bias is adjusted down to 40% for moonpearl, and 20% for morph.
We also change and consolidate the reordering algorithm in order to make it more correct (items are now guaranteed to be within their bias thresholds), and to make it easier to conditionally include more item types to be biased (e.g. sword, boots).

Narrow multiworld item bias

---

WebRandomizer/ClientApp/src/components/Upload.jsx

When storing file data to `localForage` in Upload we must avoid storing the initial null value in the case a subset of files are required (such as for SM only rando).
We might want to consider a later commit which makes the SMZ3 page only ask for the Z3 rom file if an SM rom file was already entered from the SM page.

Do not store null file data

---

Randomizer.SMZ3/Patch.cs
Randomizer.SMZ3/Text/StringTable.cs

The first custom text is (almost) the same as the default text. It turns out `end_triforce` has to be changed in the string table for anything to change at all.

Actually add custom triforce room text

---

Randomizer.Contracts/IRandomizer.cs
Randomizer.SMZ3/Randomizer.cs
Randomizer.SuperMetroid/Randomizer.cs
WebRandomizer/ClientApp/src/components/Configure.jsx

- The settings type is changed from `input` to `seed`
- The Reactstrap Input component is styled to hide the number spin buttons since this makes little sense for entering a seed number.
- Each randomizer now also throw an exception on parsing a negative number since while the `Random` class constructor can take a negative number, its absolute value is used, a behavior that can be non-obvious.
Also switched to using the `value` prop instead of `defaultValue` in `Configure`. The later is meant for "uncontrolled" react components, while the components in question in `Configure` were used in the "controlled" manner.
Credits to @avvie for identifying the issue
Closes #33

Limit the seed option to a non-negative 32 bit integer

---

Randomizer.SMZ3/Regions/Zelda/IcePalace.cs

Changes the logic for the three "east wing" locations to be on par with Z3r v31.0.4

Guard IP "east wing" against worst key use

---

WebRandomizer/ClientApp/src/components/Multiworld.jsx
WebRandomizer/ClientApp/src/components/Patch.jsx
WebRandomizer/ClientApp/src/components/Permalink.jsx
WebRandomizer/ClientApp/src/components/util/BootstrapIcon.jsx
WebRandomizer/ClientApp/src/components/util/DownloadInfoTooltip.jsx
WebRandomizer/ClientApp/src/logiclog/LogicLog.jsx
WebRandomizer/Controllers/RandomizerController.cs
WebRandomizer/Migrations/20200331220405_ChangeLogicToSettings.Designer.cs
WebRandomizer/Migrations/20200331220405_ChangeLogicToSettings.cs
WebRandomizer/Migrations/20200403180848_ChangeSeedTypeToMode.Designer.cs
WebRandomizer/Migrations/20200403180848_ChangeSeedTypeToMode.cs
WebRandomizer/Migrations/20200403183043_AddVersionToSeed.Designer.cs
WebRandomizer/Migrations/20200403183043_AddVersionToSeed.cs
WebRandomizer/Models/Seed.cs
WebRandomizer/Models/World.cs

This changes the "Logic" field on the "World" entity into "Settings" to be used for storing the settings used at seed generation time so we can display it back on permalinks and use it to generate things like the seed filename,

Add seed generation settings to the database

---

WebRandomizer/ClientApp/.env
WebRandomizer/ClientApp/package.json
WebRandomizer/ClientApp/src/components/Configure.jsx
WebRandomizer/ClientApp/src/components/Multiworld.jsx
WebRandomizer/ClientApp/src/components/Patch.jsx
WebRandomizer/ClientApp/src/components/Permalink.jsx

- Ignore no-mixed-operators globally, because relying on operator priority between `&&` and `||` should be just fine.
- Ignored empty dep array for one time `useEffect`s, because that's a perfectly valid usage pattern according to the react docs.
- Replaced switch with a trinary operator chain in `Configure`, so that there is no default case to be missing to begin with.

Make eslint happy

---

WebRandomizer/ClientApp/src/components/Multiworld.jsx
WebRandomizer/ClientApp/src/components/Seed.jsx
WebRandomizer/ClientApp/src/network/index.js

This PR addresses Issue https://github.com/tewtal/SMZ3Randomizer/issues/91
The change was extremely minor in scope, however in implementing it I realized this would break connection for anybody who had an existing incomplete session.
As a result, over half of this code change is dedicated to backwards compatibility. I tried to clearly mark that chunk of code so that it could be deleted entirely once enough time has elapsed and it's reasonably certain that all old sessions are completed/abandoned.
I'll be happy to address any feedback or concerns you may have, just let me know!

Allow Registration To Multiple Multiworlds Simultaneously

---

WebRandomizer/ClientApp/src/resources/markdown/mwinstructions.md

There are a few scenarios that can arise where a player ends up in an uncompletable Multiworld session. This documents those situations in an effort to inform new players before they learn these lessons the hard way.

Document Potential Multiworld Issues

---

Randomizer.SMZ3/Regions/SuperMetroid/Maridia/Inner.cs

The Hard and Normal requirements for Space Jump got inverted in the C# conversion. However, they are just a repeat of the CanDefeatDraygon bool, so no additional definition is needed.

Fix Space Jump requirements

---

Randomizer.SMZ3/Item.cs

Accessing Mire Portal was missing jump assist in pre-Cathedral in Hard.

Adjust Mire Portal Access

---

Randomizer.SMZ3/Regions/SuperMetroid/NorfairUpper/Crocomire.cs

CanPassBombPassages in Bubble Mountain has been missing from Normal since the beginning. When we added the Gravity requirement for going through Volcano Room, it accidently made going through Bubble Mountain to Croc require Grav in general.

Fix Croc access through Bubble Mountain

---

WebRandomizer/ClientApp/src/App.jsx
WebRandomizer/ClientApp/src/components/Configure.jsx
WebRandomizer/ClientApp/src/components/Layout.jsx
WebRandomizer/ClientApp/src/components/Multiworld.jsx
WebRandomizer/ClientApp/src/components/NavMenu.jsx
WebRandomizer/ClientApp/src/components/Patch.jsx
WebRandomizer/ClientApp/src/components/Permalink.jsx
WebRandomizer/ClientApp/src/components/Seed.jsx
WebRandomizer/ClientApp/src/components/SmHome.jsx
WebRandomizer/ClientApp/src/components/Smz3Home.jsx
WebRandomizer/ClientApp/src/components/Upload.jsx
WebRandomizer/ClientApp/src/components/util/MessageCard.jsx
WebRandomizer/ClientApp/src/file/rdc.js
WebRandomizer/ClientApp/src/file/rom.js
WebRandomizer/ClientApp/src/file/util.js
WebRandomizer/ClientApp/src/game/traits.js
WebRandomizer/ClientApp/src/network/index.js
WebRandomizer/ClientApp/src/resources/markdown/sminformation.md
WebRandomizer/ClientApp/src/resources/markdown/smz3information.md
WebRandomizer/ClientApp/src/site.js

Patch had code to resolve the specific traits for the game being served by the site. This information is needed at other places in the implementation so we lift this out to the App component. From there it is passed through a react context since it's used so ubiquitously.
Since the Configure, Permalink, and Multiworld components should only service a certain game while on the corresponding sub domain we add a check for this. If there is a mismatch we offer a link with the same path, but correct hostname. The supporting functions are hosted in a new ./site module.
Together with the game traits we simplify the snes addressing such that we can skip the booleans and only use the address mapping names (exhirom and lorom).
Minor changes:
- The default game is smz3, so the trailing branch (else …

Resolve the traits of the supported games early

---

Randomizer.SMZ3/Patch.cs

- bit 15: Race rom?
- bit 14-13: Keysanity? Currently only bit 13 matters, but we reserve two bits in case we want more fine grained settings.

Add race and keysanity bits to the seed data field

---

Randomizer.SuperMetroid/Patch.cs

We had only set this bit for SMZ3 seed patches, but naturally it should also be set in SM seed patches.
- bit 15: Race rom?

Add race bit to the SM seed data field

---

WebRandomizer/ClientApp/src/components/Spoiler.jsx

We failed at escaping special regular expression characters when constructing a regex instance. With `escapeRegExp` from lodash we save the day. Also, in Javascript, an empty string is already a falsy value so if statements can be simplified.

Sanitize spoiler log search text for use as a regular expression

---

Randomizer.CLI/FileData/Rom.cs
Randomizer.CLI/Verbs/GenSeed.cs

Refinement of PR #114 (with authorship preserved).
- Enables correct generation of SM rando rom files after the introduction of the Samus custom sprite implementation by remembering to extend the rom to 4 MB.
- Moves the SMZ3 seed options to the verb sub class so that they are not available for the SM verb.
- Provides all lower case values for the KeyShuffle api option. Option values are case insensitive, but let's use lower case for consistency.
- Make separate boolean Sword and Morph CLI parameters instead of string parameters. This makes it consistent with the existing Normal/Hard logic parameters.
- Name the Sword and Morph parameters by their corresponding api value names. As a dev tool, CLI should not hide these implementation details.
- Adds the Placement seed option to the SM verb …

Add seed options to the CLI (refined)

---

Randomizer.SMZ3/Patch.cs

Realizing this flag originate in the address space that holds multiple flags that are described as common between the games, I refactored the `WriteGameMode` method to handle all of these.

Update `Patch` to set the keysanity config flag

---

Randomizer.SMZ3/Item.cs

These two maps have no functionality (compared to the other ten which enable viewing the dungeon prize on the world map). Their slots would be better served by restoring two more Red Rupees from the vanilla item pool.

Skip the HC and GT maps in keysanity

---

Randomizer.SMZ3/Regions/SuperMetroid/Maridia/Inner.cs

Fix a bug with the sandpit items where the portal satisfies CanEnter and having the MaridiaL1 key satisfies CanReachAqueduct, without checking if you can climb Main Street and Mt. Everest.

Fix Aqueduct access rules

---

Randomizer.SMZ3/Regions/SuperMetroid/NorfairUpper/Crocomire.cs

Missing morph/UN2 check to get out of Kronic Boost area in keysanity. Also no reason to not have it in Normal with gravity and wave.

Fix Reverse Lava Dive access, add to Normal

---

Randomizer.SMZ3/Regions/SuperMetroid/NorfairLower/West.cs

Doing so greatly simplifies LN East's requirements, specifically for CanExit, and draws a clear dividing line between East and West at the Amphitheater entrance (LN1 Key).

Move Mickey Mouse missile to West LN

---

Randomizer.SMZ3/Regions/SuperMetroid/NorfairLower/East.cs

Moved Mickey Mouse to West to simplify logic, and fixed bug with CanExit that forced a gate glitch or reverse Amphitheater in Normal.

Simplify logic and fix exit bug

---

Randomizer.SMZ3/Regions/SuperMetroid/WreckedShip.cs

When going to WS via Forgotten Highway after killing Draygon and going through Cacattack Alley, the Maradia L2 key is not needed.  On hard mode, this is correctly not required.  This fixes the normal logic to match that, requiring the Maridia L2 key only when going back through the sand pits and up the toilet.

Fix Forgotten Highway access to WS on normal

---

Randomizer.SuperMetroid/Regions/Crateria/East.cs

Remove grapple/speed/space requirement from moat missiles. Add crossing the moat with Grav + IBJ/HJB to the others, to match WS CanEnter.
Still ignoring FH access for now. Also ignoring the superfluous super and bomb passage requirements on the upper items, which are covered by CanEnter.

Fix moat logic

---

Randomizer.SMZ3.Tests/Logic/Case.cs
Randomizer.SMZ3.Tests/Logic/LogicCases.cs
Randomizer.SMZ3.Tests/Logic/LogicTests.cs
Randomizer.SMZ3.Tests/Logic/SMHard.cs
Randomizer.SMZ3.Tests/Logic/SMHardKeysanity.cs
Randomizer.SMZ3.Tests/Logic/SMNormal.cs
Randomizer.SMZ3.Tests/Logic/SMNormalKeysanity.cs
Randomizer.SMZ3.Tests/Randomizer.SMZ3.Tests.csproj
Randomizer.SMZ3/Item.cs
Randomizer.SMZ3/Location.cs
Randomizer.SMZ3/Regions/SuperMetroid/Brinstar/Blue.cs
Randomizer.SMZ3/Regions/SuperMetroid/Brinstar/Pink.cs
Randomizer.SMZ3/Regions/SuperMetroid/Crateria/East.cs
Randomizer.SMZ3/Regions/SuperMetroid/Maridia/Inner.cs
Randomizer.SMZ3/Regions/SuperMetroid/NorfairLower/East.cs
Randomizer.SMZ3/Regions/SuperMetroid/NorfairLower/West.cs
Randomizer.SMZ3/Regions/SuperMetroid/NorfairUpper/Crocomire.cs
Randomizer.SMZ3/Regions/SuperMetroid/NorfairUpper/East.cs
Randomizer.SMZ3/Regions/SuperMetroid/NorfairUpper/West.cs
Randomizer.SMZ3/Regions/SuperMetroid/WreckedShip.cs
Randomizer.SMZ3/Regions/Zelda/GanonsTower.cs
Randomizer.SMZ3/Regions/Zelda/PalaceOfDarkness.cs
Randomizer.SMZ3/World.cs

As the commit mentions, having cases of progression that covers both the region's CanEnter and the logic of the location made for an O(n^2) situation that the NUnit framework handled very poorly. I had to stretch into the internals of `Location` so I could test the location logic expressions separate from the region. With that change the tests run somewhat quickly.
This PR contains some important logic changes that need as many eyes as possible for verification. @TarThoron

Logic unit tests

---

Randomizer.SMZ3/Patch.cs

I used the reserved space at `$80FF58` for some previously unwritten seed data. It's another `UShort` bitfield mapped as follows, starting from the MSB:
* `SwordLocation` filling 2 bits
* `MorphLocation` filling 2 bits
* `Goal` filling 4 bits (2 bits seems a bit small here)
* 8 reserved bits for any future nuance in the seed data
Since only 8 bits are occupied, this could just be a `Byte`. However, I suggest that all extra future seed data be written to the ROM. This way, there isn't any data loss from a filename change, and all of the data is contained in one place. I argue that this is significant for any theoretical tool that deals with SMZ3 ROMs.

Comprehensive seed data in ROM

---

Randomizer.SMZ3/Text/Scripts/General.yaml
Randomizer.SMZ3/Text/Texts.cs

Replaced the generic Keycard pedestal/tablet hint with specific hints for each Super Metroid keycard, and updated the Texts class to properly populate these hints.

Add specific ped/tablet hints for each SM keycard

---

Randomizer.SMZ3/Patch.cs

Because the reserved space were zero filled before, and not zero filling the (now smaller) space would technically not be backward compatible.

Restore config field zero fill

---

WebRandomizer/ClientApp/package.json
WebRandomizer/ClientApp/src/generate/Permalink.jsx
WebRandomizer/ClientApp/src/multiworld/Multiworld.jsx
WebRandomizer/ClientApp/src/spoiler/Spoiler.jsx
WebRandomizer/ClientApp/src/spoiler/region_ordering.js
WebRandomizer/ClientApp/src/spoiler/styled.js
WebRandomizer/ClientApp/src/ui/BootstrapIcon.jsx
WebRandomizer/ClientApp/src/util.js

Main highlights:
* Parent components check the race setting flag, either rendering the `Spoiler` or not at all.
* `Spoiler` only takes the seed guid, used to fetch all spoiler data from the spoiler api endpoint.
* Locations are no longer sorted by their id (relying on the ordinal order as received from the api), but instead grouped by a predetermined region order.
* The spoiler log is rendered using the YAML format instead of JSON. It includes a header with the game id, version, seed hash, and a meta section with (for now):
* SMZ3: Goal, SM Logic, Keysanity, Crystal and Boss Token requirements
* SM: Goal, Logic

Spoiler refactoring and log file improvement

---

Randomizer.SMZ3/Regions/SuperMetroid/Maridia/Inner.cs

Yellow Maridia has been logically accessible from the portal with just HJB or Spring for suitless movement, which would require Super Metroid Impossible style walljumping up the left side.
This change makes sure you have either Gravity or at least two of HJB, Spring, and Ice. Doesn't need a Logic Switch because Normal always has Gravity.

Ensure Crab Shaft climbable suitless

---

Randomizer.SMZ3/Regions/Zelda/GanonsTower.cs

It's been discovered that TO(GT/7) is getting rounded to TO(0) if GT is anything other than 7. This can be fixed by multiplying before dividing, thus (TO*GT)/7.

Fix GT Entry token requirement
