WebRandomizer/Startup.cs

Reverts tewtal/SMZ3Randomizer#19
Reverting this for now since the changes doesn't work in Release-mode and was causing the docker container to fail.

Revert "Make lua files download instead of open"

---

Randomizer.CLI/Verbs/GenSeed.cs
Randomizer.SMZ3/Randomizer.cs

Makes it easier to generate json files for patch and playthrough data.

Update to the CLI

---

WebRandomizer/Startup.cs

This one seems to have fell between the cracks. This one *should* work in release mode.

Link download

---

Randomizer.SMZ3/Config.cs
Randomizer.SMZ3/Filler.cs
Randomizer.SMZ3/Randomizer.cs
WebRandomizer/ClientApp/src/components/Multiworld.jsx
WebRandomizer/ClientApp/src/components/Permalink.jsx
WebRandomizer/ClientApp/src/components/Spoiler.jsx

Added support for the early sword/morph configuration options.
At some later point we might want to improve upon this to make it a bit more generic to enable placement options for arbitrary items, but right now there is no need since these are the only configuration options that will be available for a while.

Added support for the Sword/Morph placement options.

---

Randomizer.SMZ3/Regions/SuperMetroid/Crateria/East.cs
Randomizer.SMZ3/Regions/SuperMetroid/Maridia/Inner.cs
Randomizer.SMZ3/Regions/SuperMetroid/Maridia/Outer.cs
Randomizer.SMZ3/Regions/SuperMetroid/WreckedShip.cs
WebRandomizer/ClientApp/src/logiclog/brinstar/BrinstarKraid.md
WebRandomizer/ClientApp/src/logiclog/maridia/MaridiaInnerHard.md
WebRandomizer/ClientApp/src/logiclog/maridia/MaridiaInnerNormal.md

Let's talk about the logic code formatting. This what I want to see. What, if any, do you find confusing in this style? I know I have left end parenthesis trailing if they are the last parts of an expression in a location, is that an example of such a source of confusion? do you prefer to place operators after line breaks rather than at the end of lines? and so on...

Logic log fix

---

Randomizer.SMZ3/Regions/SuperMetroid/Maridia/Outer.cs

Also fixes missing Mama Turtle red door issue

Fix Access from Maridia Portal

---

Randomizer.SMZ3/Regions/SuperMetroid/Maridia/Outer.cs
WebRandomizer/ClientApp/src/logiclog/maridia/MaridiaOuterHard.md
WebRandomizer/ClientApp/src/logiclog/maridia/MaridiaOuterNormal.md

Some code formatting, and added the change to the Logic Log.

Complementary PR for the Maridia Outer logic change

---

WebRandomizer/ClientApp/src/components/Configure.jsx

Disable form autocomplete on multiworld name flields

---

WebRandomizer/ClientApp/.env
WebRandomizer/ClientApp/package.json
WebRandomizer/ClientApp/src/components/Configure.jsx
WebRandomizer/ClientApp/src/components/Multiworld.jsx
WebRandomizer/ClientApp/src/components/Patch.jsx
WebRandomizer/ClientApp/src/components/Permalink.jsx
WebRandomizer/Hubs/MultiworldHub.cs

.. rather than relying on a thrown exception.
Depends on #71

Handle missing world match explicitly in RegisterPlayer

---

Randomizer.SMZ3/Randomizer.cs
Randomizer.SuperMetroid/Randomizer.cs
WebRandomizer/ClientApp/.env
WebRandomizer/ClientApp/package.json
WebRandomizer/ClientApp/src/components/Configure.jsx
WebRandomizer/ClientApp/src/components/Connection.jsx
WebRandomizer/ClientApp/src/components/Multiworld.jsx
WebRandomizer/ClientApp/src/components/Patch.jsx
WebRandomizer/ClientApp/src/components/Permalink.jsx
WebRandomizer/ClientApp/src/components/Seed.jsx
WebRandomizer/ClientApp/src/components/Spoiler.jsx
WebRandomizer/ClientApp/src/components/Upload.jsx
WebRandomizer/ClientApp/src/components/util/PlainList.jsx
WebRandomizer/ClientApp/src/components/util/PrefixInputGroup.jsx

- Conform to the ReactJs API.
- Guard against names, for multiworld, that are not filled in, or without any letters or digits at all (this seems like a resonable requirement to me).
- Replace break tags and &nbsp; with margins and html lists since this is better for the semantics of the html structure, and in one case improves the rendering, namely the Multiworld components where break tags initially needlessly shows as a big gap between the Seed and Spoiler components.
Depends on #71

Mostly web page UI improvements

---

WebRandomizer/Controllers/Helpers.cs
WebRandomizer/Controllers/RandomizerController.cs
WebRandomizer/Migrations/20200410165808_AddSeedHash.Designer.cs
WebRandomizer/Migrations/20200410165808_AddSeedHash.cs
WebRandomizer/Models/Seed.cs

Create a new field on the Seed model that contains the seed filename hash generated from the patch data depending on game id.

Store seed hash in db at seed generation.

---

WebRandomizer/ClientApp/public/index.html
WebRandomizer/ClientApp/src/App.jsx
WebRandomizer/ClientApp/src/components/Home.jsx
WebRandomizer/ClientApp/src/components/Layout.jsx
WebRandomizer/ClientApp/src/components/NavMenu.jsx
WebRandomizer/ClientApp/src/components/SmHome.jsx
WebRandomizer/ClientApp/src/resources/markdown/mwinstructions.md
WebRandomizer/ClientApp/src/resources/markdown/resources.md
WebRandomizer/ClientApp/src/resources/markdown/smchangelog.md
WebRandomizer/ClientApp/src/resources/markdown/sminformation.md
WebRandomizer/ClientApp/src/resources/markdown/smz3changelog.md
WebRandomizer/ClientApp/src/resources/markdown/smz3information.md

Added support for different pages for sm and smz3.
Moved some information into a help dropdown menu.
Changed the front page to look a bit nicer for smz3.

Update and add information to the site

---

WebRandomizer/ClientApp/package.json
WebRandomizer/ClientApp/src/index.js
WebRandomizer/ClientApp/src/polyfill/TextDecoder.js

Adds support for IE11 and Edge for the Randomizer.

Polyfill missing IE/Edge browser features.

---

Randomizer.SMZ3.Tests/StringTableTests.cs
Randomizer.SMZ3/Item.cs
Randomizer.SMZ3/Randomizer.cs
Randomizer.Shared/Contracts/IRandomizer.cs
Randomizer.SuperMetroid/Randomizer.cs
WebRandomizer/Controllers/SeedController.cs
WebRandomizer/Controllers/SpoilerController.cs

This adds a new back end API endpoint for getting full spoiler information for a given (non-race) seed.
Some additions has been made to the randomizer cores to enable the controller to more easily generate this information.

Implement a new back end API for full spoiler log generation

---

WebRandomizer/ClientApp/src/components/Spoiler.jsx

Added new features to the Spoiler log component to use the new spoiler log API.
It can now show the full spoiler for every item split into regions and it includes a search box to filter the results.

New spoiler log

---

Randomizer.SMZ3/Regions/SuperMetroid/Crateria/East.cs

It's annoying, but you can ride the trippers to get Missiles in The Sky with nothing.

Simplify code and remove jump assist from top missile

---

Randomizer.SMZ3/Item.cs
Randomizer.SMZ3/Regions/SuperMetroid/Brinstar/Pink.cs
Randomizer.SMZ3/Regions/SuperMetroid/Crateria/Central.cs
Randomizer.SMZ3/Regions/SuperMetroid/Crateria/East.cs
Randomizer.SMZ3/Regions/SuperMetroid/Crateria/West.cs
Randomizer.SMZ3/Regions/SuperMetroid/Maridia/Inner.cs
Randomizer.SMZ3/Regions/SuperMetroid/NorfairLower/East.cs
Randomizer.SMZ3/Regions/SuperMetroid/NorfairLower/West.cs
Randomizer.SMZ3/Regions/SuperMetroid/NorfairUpper/Crocomire.cs
Randomizer.SMZ3/Regions/SuperMetroid/NorfairUpper/East.cs
Randomizer.SMZ3/Regions/SuperMetroid/NorfairUpper/West.cs
Randomizer.SMZ3/Regions/SuperMetroid/WreckedShip.cs

.. as well as fix a missing item description, and move Lava room from UN East to UN West

Adjust keysanity logic

---

Randomizer.SMZ3/Patch.cs
Randomizer.SMZ3/Randomizer.cs
Randomizer.SMZ3/Text/Dialog.cs
Randomizer.SuperMetroid/Patch.cs
Randomizer.SuperMetroid/Randomizer.cs
WebRandomizer/ClientApp/src/file/rom.js

Depends on https://github.com/tewtal/alttp_sm_combo_randomizer_rom/pull/50

Allow for case sensitive player names

---

Randomizer.SMZ3/Regions/SuperMetroid/Crateria/East.cs

Hopefully the last adjustment. Matching the WS CanEnter.

More Forgotten Highway stuff

---

Randomizer.SMZ3/Regions/SuperMetroid/NorfairLower/West.cs

Mickey Mouse in logic with just pbs is a bad thing.

Fix missing ()

---

Randomizer.SMZ3/Regions/SuperMetroid/NorfairLower/West.cs

Re-account for accessing via Lava Dive
Make sure all routes can break the bomb floors.

House of Mouse is broken.

---

Randomizer.SuperMetroid/Regions/NorfairUpper/West.cs

Hi Jump needs to be able to get back out
(This is SM only, not SMZ3)

Forced softlocks are bad

---

.github/workflows/mw-beta.yml
.github/workflows/pullrequest.yml
Dockerfile
Randomizer.CLI/Randomizer.CLI.csproj
Randomizer.SMZ3.Tests/Randomizer.SMZ3.Tests.csproj
Randomizer.SMZ3.Tests/Text/DialogTests.cs
Randomizer.SMZ3/Randomizer.SMZ3.csproj
Randomizer.Shared/Randomizer.Shared.csproj
Randomizer.SuperMetroid.Tests/Randomizer.SuperMetroid.Tests.csproj
Randomizer.SuperMetroid/Randomizer.SuperMetroid.csproj
WebGameService/WebGameService.csproj
WebRandomizer/WebRandomizer.csproj

This PR will upgrade from .NET 5 to .NET 6.

Upgrade projects and solutions to .NET 6

---

Randomizer.SMZ3/Patch.cs
Randomizer.SMZ3/Playthrough.cs
Randomizer.SMZ3/Randomizer.cs
Randomizer.SMZ3/Region.cs
Randomizer.SMZ3/Regions/SuperMetroid/Brinstar/Kraid.cs
Randomizer.SMZ3/Regions/SuperMetroid/Maridia/Inner.cs
Randomizer.SMZ3/Regions/SuperMetroid/NorfairLower/East.cs
Randomizer.SMZ3/Regions/SuperMetroid/WreckedShip.cs
Randomizer.SMZ3/Regions/Zelda/GanonsTower.cs
Randomizer.SMZ3/Regions/Zelda/IcePalace.cs
Randomizer.SMZ3/Regions/Zelda/PalaceOfDarkness.cs
Randomizer.SMZ3/World.cs

This is an initial implementation of cross-game rewards.
There are still more things to implement, but this PR will allow for a beta-build that can be tested and given feeback on.

Initial support for cross-game rewards

---

Randomizer.CLI/Randomizer.CLI.csproj
Randomizer.SMZ3.Tests/Logic/LogicTests.cs
Randomizer.SMZ3.Tests/Logic/SMNormal.cs
Randomizer.SMZ3.Tests/Text/DialogTests.cs
Randomizer.SMZ3/Playthrough.cs
Randomizer.SMZ3/Randomizer.cs
Randomizer.SMZ3/Region.cs
Randomizer.SMZ3/Regions/Zelda/GanonsTower.cs
Randomizer.SMZ3/Regions/Zelda/IcePalace.cs
Randomizer.SMZ3/Regions/Zelda/LightWorld/NorthWest.cs
Randomizer.SMZ3/World.cs
Randomizer.SuperMetroid/Playthrough.cs
Randomizer.SuperMetroid/Randomizer.cs

- Logic tests were broken due to recent changes. Adjusted the test fixture.
- The `Playthrough` can now navigate Ice Palace, while the `Filler` can still get the key logic right.
- The github PRs *should* stop complaining about platforms for the CLI.

Fix logic tests and solve IP key logic issue

---

WebRandomizer/ClientApp/src/multiworld/Game.jsx
WebRandomizer/ClientApp/src/multiworld/Multiworld.jsx
WebRandomizer/ClientApp/src/multiworld/styled.js
WebRandomizer/ClientApp/src/ui/BootstrapIcon.jsx
WebRandomizer/ClientApp/src/ui/ColoredIcon.jsx

At least for consistent UI, maybe because they look better?
Also some repairs of minor mistakes/oversights.

SVG icon contributions to replace the "quick and dirty" unicode picks

---

Randomizer.SMZ3/Text/Scripts/General.yaml
Randomizer.SMZ3/Text/Texts.cs

.. which reads:
> You can now
> find your way
> to the stars!

Add a pedestal/tablet hint for SM maps

---

.github/workflows/production.yml

(Untested, unfamiliar with the syntax. Please bug me if it's incorrect.)

Correct Ganon sign text on AllDungeonsDefeatMotherBrain goal
